// client/react-js/src/components/post/PostForm.js
import FieldCardHeader from '../field-card/FieldCardHeader';
import FullFieldCard from '../field-card/FullFieldCard';
import '../../App.css';
import { useState } from 'react';
import { CREATE_POST } from '../../queries';
import { graphqlQuery } from '../../graphql';

function PostForm({ postData }) {
    // Set Up
    const [postBody, setPostBody] = useState('')

    // Handlers
    const createPost = () => {
      const variables = { userId: "33", body: postBody };
      graphqlQuery(CREATE_POST, variables).then((result) => {
          console.log(`result: ${JSON.stringify(result)}`)
          window.location.reload(true);
      })
      .catch((error) => {
          alert(JSON.stringify(error))
      })
    }

    // Return Component
    return (
        <FullFieldCard>
            <FieldCardHeader>
                <div class="post-form-header">
                    Write a Post
                </div>
            </FieldCardHeader>
            <input id="post-form-field" class="post-form-field px-2 mb-2" placeholder="Something you wanna share? Feel free to write it here!" value={postBody} onChange={(e) => setPostBody(e.target.value)}/>
            <button class="post-form-button" type="button" onClick={ createPost }>Post</button>
        </FullFieldCard>
    );
}

export default PostForm;

// client/angular-js/src/app/post-form/post-form.component.ts
import { Component } from '@angular/core';
import { FieldCardBodyComponent } from '../field-card-body/field-card-body.component';
import { FieldCardBottomSpaceComponent } from '../field-card-bottom-space/field-card-bottom-space.component';
import { FieldCardComponent } from '../field-card/field-card.component';
import { FieldCardExtendedBottomSpaceComponent } from '../field-card-extended-bottom-space/field-card-extended-bottom-space.component';
import { FieldCardHeaderComponent } from '../field-card-header/field-card-header.component';
import { FieldCardLiftedSpaceComponent } from '../field-card-lifted-space/field-card-lifted-space.component';
import { FieldCardTopSpaceComponent } from '../field-card-top-space/field-card-top-space.component';
import { FullFieldCardComponent } from '../full-field-card/full-field-card.component';
import { FormsModule } from '@angular/forms'
import { Apollo } from 'apollo-angular';
import { CREATE_POST } from '../graphql.operations';

@Component({
  selector: 'app-post-form',
  standalone: true,
  imports: [FormsModule,FullFieldCardComponent,FieldCardBodyComponent, FieldCardBottomSpaceComponent, FieldCardComponent,FieldCardExtendedBottomSpaceComponent,FieldCardHeaderComponent, FieldCardLiftedSpaceComponent, FieldCardTopSpaceComponent],
  templateUrl: './post-form.component.html',
  styleUrl: './post-form.component.css'
})
export class PostFormComponent {
  postBody: String;

  constructor(private apollo: Apollo) {
    this.postBody = ''
  }

  createPost() {
    if (!this.postBody) {
      alert("Post body must not be blank")
    }
    const variables = { userId: "33", body: this.postBody }
    this.apollo.mutate({ mutation: CREATE_POST, variables }).subscribe()
    window.location.reload()
  }
}

<app-full-field-card>
    <app-field-card-header>
        <div class="post-form-header">
            Write a Post
        </div>
    </app-field-card-header>
    <input id="post-form-field" type="text" class="post-form-field px-2 mb-2" placeholder="Something you wanna share? Feel free to write it here!" [(ngModel)]="postBody"/>
    <button class="post-form-button" type="button" (click)="this.createPost()">Post</button>
</app-full-field-card>
