// client/react-js/src/components/SiteRightBody.js
import { useEffect, useState } from 'react';
import '../App.css';
import ProfileBoxContainer from './ProfileBoxContainer';
import FieldCard from './field-card/FieldCard';
import FieldCardBody from './field-card/FieldCardBody';
import FieldCardBottomSpace from './field-card/FieldCardBottomSpace';
import FieldCardHeader from './field-card/FieldCardHeader';
import FieldCardLiftedSpace from './field-card/FieldCardLiftedSpace';
import FieldCardTopSpace from './field-card/FieldCardTopSpace';
import { GET_NEWS_POSTS, GET_USER } from '../queries';
import { graphqlQuery } from '../graphql';
import Post from './post/Post';

function SiteRightBody() {
    // Set Up
    const [isLoading, setIsLoading] = useState(false)
    const [postsData, setPostsData] = useState([])

    // Use Effects
    useEffect(() => {
        graphqlQuery(GET_NEWS_POSTS).then((result) => {
            console.log(`result: ${JSON.stringify(result)}`)
            setPostsData(result.newsPosts)
            setIsLoading(false)
        })
        .catch((error) => {
            alert(JSON.stringify(error))
        })
    })

    // Return Component
    return (
        <div class="w-100">
            <div class="page-header">News</div>
            <div class="w-100">
                {isLoading ? (
                    <p>Loading posts...</p>
                ): (
                    <>
                        {postsData.map((post) => (
                            <Post postData={post} author={post.user.name} body={post.body} numberOfLikes={post.numberOfLikes} numberOfComments={post.numberOfComments} />
                        ))}
                    </>
                )}
            </div>
        </div>
    );
}

export default SiteRightBody;

// frontend/angular-js/src/app/site-right-body/site-right-body.component.ts
import { Component } from '@angular/core';
import { Apollo } from 'apollo-angular';
import { GET_NEWS_POSTS } from '../graphql.operations';
import { PostComponent } from '../post/post.component';

@Component({
  selector: 'app-site-right-body',
  standalone: true,
  imports: [PostComponent],
  templateUrl: './site-right-body.component.html',
  styleUrl: './site-right-body.component.css'
})
export class SiteRightBodyComponent {
  isLoading: Boolean = true
  postsData: any;

  constructor(private apollo: Apollo) {
    // Do Nothing
  }

  ngOnInit(): void {
    this.apollo.watchQuery({
      query: GET_NEWS_POSTS
    }).valueChanges.subscribe(({data, error}: any) => {
      this.postsData = data.newsPosts
      this.isLoading = false
    })
  }
}

<div class="w-100">
    <div class="page-header">News</div>
    <div class="w-100">
        @if (isLoading) {
            <p>Loading posts....</p> 
        } 
        @else {
            @for (post of postsData; track post) {
                <app-post [postData]="post" [author]="post.user.name" [body]="post.body" [numberOfLikes]="post.numberOfLikes" [numberOfComments]="post.numberOfComments"/>
            }
        }
    </div>
</div>
