// frontend/angular-js/src/app/comment-form/comment-form.component.ts
import { Component, Input } from '@angular/core';
import { Apollo } from 'apollo-angular';
import { CREATE_COMMENT } from '../graphql.operations';
import { FormsModule } from '@angular/forms'
import { FieldCardHeaderComponent } from '../field-card-header/field-card-header.component';

@Component({
  selector: 'app-comment-form',
  standalone: true,
  imports: [FormsModule,FieldCardHeaderComponent],
  templateUrl: './comment-form.component.html',
  styleUrl: './comment-form.component.css'
})
export class CommentFormComponent {
  @Input()
  postData: any;
  commentBody: String;

  constructor(private apollo: Apollo) {
    this.commentBody = ''
  }

  createComment() {
    if (!this.commentBody) {
      alert("Comment body must not be blank")
    }
    const variables = { userId: "33", postId: this.postData.id, body: this.commentBody }
    this.apollo.mutate({ mutation: CREATE_COMMENT, variables }).subscribe()
    window.location.reload()
  }
}

// frontend/react-js/src/components/comment/CommentForm.js
import FieldCardHeader from '../field-card/FieldCardHeader';
import FullFieldCard from '../field-card/FullFieldCard';
import '../../App.css';
import { useState } from 'react';
import { CREATE_COMMENT } from '../../queries';
import { graphqlQuery } from '../../graphql';

function CommentForm({ postData }) {
    // Set Up
    const [commentBody, setCommentBody] = useState('')

    // Handlers
    const createComment = () => {
      const variables = { userId: "33", postId: postData.id, body: commentBody };
      graphqlQuery(CREATE_COMMENT, variables).then((result) => {
          console.log(`result: ${JSON.stringify(result)}`)
          window.location.reload(true);
      })
      .catch((error) => {
          alert(JSON.stringify(error))
      })
    }

    // Return Component
    return (
        <FullFieldCard>
            <FieldCardHeader>
                <div class="post-form-header">
                    Write a Comment
                </div>
            </FieldCardHeader>
            <input id="post-form-field" class="post-form-field px-2 mb-2" placeholder="Write a comment here!" value={commentBody} onChange={(e) => setCommentBody(e.target.value)}/>
            <button class="post-form-button" type="button" onClick={ createComment }>Post Comment</button>
        </FullFieldCard>
    );
}

export default CommentForm;
