// client/react-js/src/components/SiteLeftBody.js
import { useEffect, useState } from 'react';
import '../App.css';
import ProfileBoxContainer from './ProfileBoxContainer';
import FieldCard from './field-card/FieldCard';
import FieldCardBody from './field-card/FieldCardBody';
import FieldCardBottomSpace from './field-card/FieldCardBottomSpace';
import FieldCardHeader from './field-card/FieldCardHeader';
import FieldCardLiftedSpace from './field-card/FieldCardLiftedSpace';
import FieldCardTopSpace from './field-card/FieldCardTopSpace';
import { GET_USER } from '../queries';
import { graphqlQuery } from '../graphql';

function SiteLeftBody() {
    // Set Up
    const [userData, setUserData] = useState(null)

    // Use Effects
    useEffect(() => {
        graphqlQuery(GET_USER, { userId: "33" }).then((result) => {
            console.log(`result: ${JSON.stringify(result)}`)
            setUserData(result.userById[0])
        })
        .catch((error) => {
            alert(JSON.stringify(error))
        })
    })

    // Return Component
    return (
        <div class="w-100">
            <div class="page-header">My Toffeechat</div>
            {userData && (
                <>
                    <FieldCard>
                        <FieldCardTopSpace>
                            <FieldCardHeader>
                                <ProfileBoxContainer />
                            </FieldCardHeader>
                            <br />
                            <FieldCardBody>
                                { userData.bio }
                            </FieldCardBody>
                        </FieldCardTopSpace>
                        <FieldCardLiftedSpace>
                            <div>
                                <b>Number of Posts: </b> {userData.numberOfAuthoredPosts}
                            </div>
                        </FieldCardLiftedSpace>
                        <FieldCardLiftedSpace>
                            <div>
                                <b>Number of Comments: </b> {userData.numberOfReceivedComments}
                            </div>
                        </FieldCardLiftedSpace>
                        <FieldCardBottomSpace>
                            <div>
                                <b>Number of Likes: </b> {userData.numberOfReceivedLikes}
                            </div>
                        </FieldCardBottomSpace>
                    </FieldCard>
                    <br />
                    <FieldCard>
                        <FieldCardTopSpace>
                            <FieldCardHeader>
                                <div class="profile-box-name">Activity</div>
                            </FieldCardHeader>
                            <FieldCardBody>
                                This shows the total likes and comments that the user <i>"Guest"</i> has authored:
                            </FieldCardBody>
                        </FieldCardTopSpace>
                        <FieldCardLiftedSpace>
                            <div>
                                <b>Authored Likes: </b> {userData.numberOfAuthoredLikes}
                            </div>
                        </FieldCardLiftedSpace>
                        <FieldCardLiftedSpace>
                            <div>
                                <b>Authored Comments: </b> {userData.numberOfAuthoredComments}
                            </div>
                        </FieldCardLiftedSpace>
                    </FieldCard>
                </>
            )}
        </div>
    );
}

export default SiteLeftBody;

// frontend/angular-js/src/app/site-left-body/site-left-body.component.ts
import { Component, OnInit } from '@angular/core';
import { FieldCardBodyComponent } from '../field-card-body/field-card-body.component';
import { FieldCardBottomSpaceComponent } from '../field-card-bottom-space/field-card-bottom-space.component';
import { FieldCardComponent } from '../field-card/field-card.component';
import { FieldCardExtendedBottomSpaceComponent } from '../field-card-extended-bottom-space/field-card-extended-bottom-space.component';
import { FieldCardHeaderComponent } from '../field-card-header/field-card-header.component';
import { FieldCardLiftedSpaceComponent } from '../field-card-lifted-space/field-card-lifted-space.component';
import { FieldCardTopSpaceComponent } from '../field-card-top-space/field-card-top-space.component';
import { ProfileBoxContainerComponent } from '../profile-box-container/profile-box-container.component';
import { Apollo } from 'apollo-angular';
import { GET_USER } from '../graphql.operations';

@Component({
  selector: 'app-site-left-body',
  standalone: true,
  imports: [FieldCardBodyComponent, FieldCardBottomSpaceComponent, FieldCardComponent, FieldCardExtendedBottomSpaceComponent, FieldCardHeaderComponent, FieldCardLiftedSpaceComponent, FieldCardTopSpaceComponent, ProfileBoxContainerComponent],
  templateUrl: './site-left-body.component.html',
  styleUrl: './site-left-body.component.css'
})
export class SiteLeftBodyComponent implements OnInit {
  userData: any

  constructor(private apollo: Apollo) {
    // Do Nothing
  }

  ngOnInit(): void {
    this.apollo.watchQuery({
      query: GET_USER,
      variables: { userId: "33" }
    }).valueChanges.subscribe(({data, error}: any) => {
      this.userData = data.userById[0]
    })
  }
}

<div class="w-100">
    <div class="page-header">My Toffeechat</div>
    <app-field-card>
        <app-field-card-top-space>
            <app-field-card-header>
                <app-profile-box-container />
            </app-field-card-header>
            <br />
            <app-field-card-body>
                {{ this.userData.bio }}
            </app-field-card-body>
        </app-field-card-top-space>
        <app-field-card-lifted-space>
            <div>
                <b>Number of Posts: </b> {{this.userData.numberOfAuthoredPosts}}
            </div>
        </app-field-card-lifted-space>
        <app-field-card-lifted-space>
            <div>
                <b>Number of Comments: </b> {{this.userData.numberOfReceivedComments}}
            </div>
        </app-field-card-lifted-space>
        <app-field-card-bottom-space>
            <div>
                <b>Number of Likes: </b> {{this.userData.numberOfReceivedLikes}}
            </div>
        </app-field-card-bottom-space>
    </app-field-card>
    <br />
    <app-field-card>
        <app-field-card-top-space>
            <app-field-card-header>
                <div class="profile-box-name">Activity</div>
            </app-field-card-header>
            <app-field-card-body>
                This shows the total likes and comments that the user <i>"Guest"</i> has authored:
            </app-field-card-body>
        </app-field-card-top-space>
        <app-field-card-lifted-space>
            <div>
                <b>Authored Likes: </b> {{this.userData.numberOfAuthoredLikes}}
            </div>
        </app-field-card-lifted-space>
        <app-field-card-lifted-space>
            <div>
                <b>Authored Comments: </b> {{this.userData.numberOfAuthoredComments}}
            </div>
        </app-field-card-lifted-space>
    </app-field-card>
</div>
